### PR TITLE
Adds Symbiota selected schema tables as CSVs

### LINKED ISSUE #85: Symbiota: Reformat exports into CSV per table
The sql file dump of the DB makes it awkward to mix this into a shared DB, where CSV per table exports are easier allowing a simple script to bring it in (e.g. [BGBM example](https://github.com/gbif/model-material/blob/master/gbif/load-bgbm.sql)).

### PR DESCRIPTION
**Pull request by arbolitoloco**
Attempts to resolve #85

### CODE REVIEW

**Comment by timrobertson100** [comment]
Thanks @arbolitoloco 

Can you please delete everything that is no longer required? There are now 2 DB dumps and 3 sets of CSV files. There should be just one set of output CSVs that contains everything, a readme, and the source data.

**Comment by timrobertson100** [comment]
Thanks @arbolitoloco ! I haven't merged but looking at the files changes it looks great.

Before I merge can you please confirm there are no changes on README.md to make? I notice there are a few comments in README_pt2 (e.g. "PROBLEM:....") which will be lost when merged. 

Thank you

**Comment by timrobertson100** [comment]
@themerekat @arbolitoloco 
Should I merge this one first, and then the other PR please?

**Comment by themerekat** [comment]
@timrobertson100 , yes, I think so! Let us know if any issues arise because of this.

**Comment by timrobertson100** [comment]
Thanks - let's find out

**Pull request merged**
